[project]
site_name = "spark-joinery"
site_description = "spark-joinery documentation"
site_author = "Connor Charles"

[project.theme]
language = "en"
features = [
    "content.code.copy",
    "navigation.footer",
    "navigation.instant",
    "search.highlight",
]
